### ISSUE TITLE
rais doesn't respect raiseExceptions(false)

### ISSUE THREAD

**Issue by mbrevda** [josegonzalez/php-dotenv#10]
Parse throws errors for lots of FS related issues. Shouldn't these be silenceable by `raiseExceptions(false)`? I.e. if a .env file isn't found, let parse() fail gracefully and without making a fuss.

**Comment by josegonzalez** [comment]
What does it currently do re: "errors"?

**Comment by AD7six** [comment]
I can guess it's because the [example parses before calling raiseExceptions](https://github.com/josegonzalez/php-dotenv#turning-off-exceptions).
```
www-data @ dev [ /home/andy/repos/josegonzalez/php-dotenv ] (master %=)
-> cat example.php 
<?php

require 'vendor/autoload.php';

echo "one:\n";
$Loader = (new josegonzalez\Dotenv\Loader('path/to/.env'))
  ->raiseExceptions(false)
  ->parse();
echo "one loaded.\n";

echo "two:\n";
$Loader = (new josegonzalez\Dotenv\Loader('path/to/.env'))
  ->parse()
  ->raiseExceptions(false); # Irrelevant/too late
echo "two loaded.\n";
www-data @ dev [ /home/andy/repos/josegonzalez/php-dotenv ] (master %=)
-> php example.php 
one:
one loaded.
two:

Fatal error: Uncaught exception 'InvalidArgumentException' with message 'Environment file 'path/to/.env' is not found.' in /home/andy/repos/josegonzalez/php-dotenv/src/josegonzalez/Dotenv/Loader.php on line 340

InvalidArgumentException: Environment file 'path/to/.env' is not found. in /home/andy/repos/josegonzalez/php-dotenv/src/josegonzalez/Dotenv/Loader.php on line 340

Call Stack:
    0.0001     225144   1. {main}() /home/andy/repos/josegonzalez/php-dotenv/example.php:0
    0.0015     377328   2. josegonzalez\Dotenv\Loader->parse() /home/andy/repos/josegonzalez/php-dotenv/example.php:13
    0.0015     377680   3. josegonzalez\Dotenv\Loader->raise() /home/andy/repos/josegonzalez/php-dotenv/src/josegonzalez/Dotenv/Loader.php:101

www-data @ dev [ /home/andy/repos/josegonzalez/php-dotenv ] (master %=)
-> 
```

So copy-and-paste from the readme means it "throws errors for lots of FS related issues".

**Comment by josegonzalez** [comment]
Heh oops.

**Comment by mbrevda** [comment]
This doesn't address the issues. A, the order isn't definable when loading statically, B. see [this](https://github.com/josegonzalez/php-dotenv/blob/master/src/josegonzalez/Dotenv/Loader.php#L97) - that will STILL trown an error. There should be some way for it to fail gracefully (i.e. 'path to .evn not found, exiting') and silently without blowing up.

**Comment by AD7six** [comment]
@mbrevda please see the output from my previous comment and note the following:

> -> php example.php 
> one:
> one loaded.

The file it loaded doesn't exist and no "blowing up" was to be seen. Not even silently =).

Alternatively provide both:

 * A code example
 * Evidence of the aftermath following "blowing up"

**Comment by josegonzalez** [comment]
@mbrevda My latest commit should fix it. In the future, a code sample to replicate your issue would be highly useful, as there was otherwise no way for me to know what was blowing up for you.

**Comment by mbrevda** [comment]
Copy this to a file:
```php
<?php

require __DIR__ . '/vendor/autoload.php';

josegonzalez\Dotenv\Loader::load([
    'raiseExceptions' => false,
    'filepath'        => $path . '/.env',
    'putenv'          => false,
    'skipExisting'    => ['putenv']
]);
```

run `composer require josegonzalez/dotenv` and then `php test.php`.

You'll get a bunch of FS related errors. It would be nice if a missing .env can fail silently.

**Comment by AD7six** [comment]
@mbrevda I suggest a pull request with a test case =). Looks like [a simple typo](https://github.com/josegonzalez/php-dotenv/commit/a2d32cac80d468ec70ccaa0dbf8f5f61de5da1b3#diff-51f049d03b572deb3fe1cf933a3e2f36R60)

**Comment by mbrevda** [comment]
I'm not sure you understand the issue. What is the typo?

**Comment by AD7six** [comment]
@mbrevda If I tell you will you create a PR with a test case =)?

**Comment by mbrevda** [comment]
I'm working on that right now

**Comment by AD7six** [comment]
k. `$options` isn't a boolean - and cast to a boolean will always be true.

**Comment by mbrevda** [comment]
Which option is that @AD7six ?

**Comment by AD7six** [comment]
Maybe the one on the line I linked to @mbrevda. **Look** at the type of the variable `$options` and **look** at the method signature for `raiseExceptions`.

**Comment by mbrevda** [comment]
@AD7six are you enjoying this? It would be more helpful if you answer the question directly instead of teasing.

**Comment by AD7six** [comment]
You mean like complaining something's broken and taking days to point out how (and even then not showing the output) ;)?

No. I'm not enjoying it, but I'll leave it to you now.

**Comment by mbrevda** [comment]
@AD7six I'm sorry your having a bad day. Thanks for trying though!

**Comment by mbrevda** [comment]
@josegonzalez I think I see what happening here. You fix mostly fixed my issue, but it seems to be missing one tiny thing. #12 should fix it.
