### ISSUE TITLE
Stable Release?

### ISSUE THREAD

**Issue by pmjones** [josegonzalez/php-dotenv#19]
Hey there -- I'd like to start moving [Radar](https://github.com/radarphp/Radar.Project) to a stable release, but good practice suggests that Radar can't be stable until its dependencies are. Since we use php-dotenv, what are the chances of php-dotenv going stable in near future?

**Comment by josegonzalez** [comment]
[Nailed it](https://github.com/josegonzalez/php-dotenv/releases/tag/1.0.0)

**Comment by pmjones** [comment]
WELL NOW

**Comment by josegonzalez** [comment]
WOULD HELP IF THE BUILD PASSED

**Comment by pmjones** [comment]
Yes that would be preferable.

**Comment by josegonzalez** [comment]
I swear it works fine, I blame travis:

![derp](https://s3.amazonaws.com/f.cl.ly/items/0O2p271626210O1T2H1s/Image%202015-05-28%20at%205.07.04%20PM.png)

**Comment by pmjones** [comment]
Look like travis is still thinking about it. Patience :-)

**Comment by josegonzalez** [comment]
Oh, I mean that master branch passes, just that the icon still says it fails. Same commit with a tag shows the proper badge:

- master: ![](https://api.travis-ci.org/josegonzalez/php-dotenv.png?branch=master)
- 0.7.1: ![](https://api.travis-ci.org/josegonzalez/php-dotenv.png?branch=0.7.1)

**Comment by pmjones** [comment]
Oh, yes, I've seen this myself. There is sometimes some lag.
