### ISSUE TITLE
A 5x branch?

### ISSUE THREAD

**Issue by holisticnetworking** [josegonzalez/php-dotenv#34]
Looks like your requirements went up to PHP 7.0. Not sure why that would be the minimum required version for your plugin, but it seemed to work just fine for 5.x versions?

Regardless, if you're going to continue developing with a 7.0 requirement, can you please also provide a 5.x branch for those of us who want it?

**Comment by josegonzalez** [comment]
You can use the 2.x release, which supports PHP 5 just fine.
