### ISSUE TITLE
Allow source .env.default in .env files

### ISSUE THREAD

**Issue by stoatally** [josegonzalez/php-dotenv#35]
It would be good if `source .env.default` could either be ignored when parsing, or used to include the definitions from that file as well.

It would make it possible to just `source .env` and get the default environment plus any overrides or additions.

**Comment by josegonzalez** [comment]
Thats an upstream thing in [m1/env](https://github.com/m1/env), and I would file it there. We don't actually parse files here, just make an awesome interface on top of the `.env` parser.
