### ISSUE TITLE
Make php-dontenv work with older php versions

### ISSUE THREAD

**Issue by robert197** [josegonzalez/php-dotenv#36]
This extension used to work for php 5.3+.
It would be nice if we could make it work with other php versions than php 7.0+.
This way we could integrate php-dontenv in other frameworks. e.g. testing-frameworks.

**Comment by josegonzalez** [comment]
You can use release 2.1.0. The latest `3.x` line simply adds support for `apache_getenv` and `apache_setenv`, which are not testable below 7.x, hence why I dropped support.

**Comment by josegonzalez** [comment]
I'm going to lower the version supported by not requiring tests for `apache_*` methods. I'll consider them untested in lower than 7.0, but all the logic should work fine.

**Comment by josegonzalez** [comment]
https://github.com/josegonzalez/php-dotenv/pull/38
