### ISSUE TITLE
Overriding defaults

### ISSUE THREAD

**Issue by johnrobertporter** [josegonzalez/php-dotenv#37]
https://github.com/josegonzalez/php-dotenv/blob/master/src/josegonzalez/Dotenv/Loader.php#L220

I was under the impression that this package allowed merging of values from all files in the filepaths array. I see now that it doesn't.

Is there any chance this could be altered to merge and replace instead of just replace?

**Comment by josegonzalez** [comment]
Would you be fine with making that an opt-in not default?

**Comment by johnrobertporter** [comment]
After further reading of the code (I extended the class) I noticed that it's handled inside the loop. That got me thinking, that the api could be extended to allow custom processing of the file contents within that loop?

I'm not sure if that isn't overthinking it though.

An option to allow continuing the loop instead of breaking it would be ok though :D

**Comment by tanakahisateru** [comment]
My workaround:

```php
$dotenvLoader = new josegonzalez\Dotenv\Loader();
foreach ([
    __DIR__ . '/../.env',
    __DIR__ . '/../.env.default',
] as $path) {
    $dotenvLoader->setFilepath($path)->parse()->skipExisting()->toEnv()->putenv();
}
```

**Comment by stefanvangastel** [comment]
Same solution here. We wanted to use DotEnv combined with Docker so sometimes have an .env file and with defaults and sometimes 'overwrite' or pre-set env var's with Docker. This resulted in errors or overwriting the Docker pre-defined env var's.

`skipExisting()` solved this issue so the Docker env var's remain intact.

**Comment by josegonzalez** [comment]
Closing as a workaround exists :)
