### ISSUE TITLE
NOT EVEN ONE EXAMPLE 

### ISSUE THREAD

**Issue by alialwahish** [josegonzalez/php-dotenv#44]
Now I know why this is not popular because you don't even have one example on how to call the variables like just one to **RETRIEVE  a VALUE ** from the damn .env file  !!! 
are we using getenv() or env() 
I'm a beginner and there's no shame in that I can't use your library what so ever and it's so obvious why there's not even one stackoverflow issue with your library

**Comment by alialwahish** [comment]
I'll just answer myself for any other one there looking for the same issue ! 
```
$Loader = new josegonzalez\Dotenv\Loader(ROOT .'.env');

// Parse the .env file
$Loader->parse();
// Send the parsed .env file to the $_ENV variable
$Loader->toEnv();


var_dump($_ENV['VARIABLE NAME IN ENV FILE']);
```
was it really hard for you josegonzalez to add this line for starters don't know their way to this, however I don't know and don't care why you didn't put this in the documentation but let me just tell you that one day you were a beginner with zero knowledge !!!

regards 
Ali

**Comment by josegonzalez** [comment]
Hi @alialwahish.

A few things:

- Pull requests to the documentation are welcome. The section for `$_ENV` is documented [here](https://github.com/josegonzalez/php-dotenv#adding-to-_env).
  - Actually, I don't want anything to do with you, so pull requests are not welcome from you.
- I don't appreciate the tone in your comments. You've neither paid for my time nor my library, and therefore aren't owed anything. Your rudeness is extremely unwelcome.
- You are welcome to use any other library out there. In fact, I'd encourage you to never use anything I've ever worked on or contributed to.

Never contact me again.
