### ISSUE TITLE
Fatal error: Uncaught LogicException: Key "DEBUG" has already been defined in getenv() in

### ISSUE THREAD

**Issue by thomaskanzig** [josegonzalez/php-dotenv#48]
I have this error:
`Fatal error: Uncaught LogicException: Key "DEBUG" has already been defined in getenv() in /Users/thomaskanzig/Documents/www/bonom/vendor/josegonzalez/dotenv/src/josegonzalez/Dotenv/Loader.php on line 434`

Why this happen? 
Help please.

**Comment by josegonzalez** [comment]
This means the environment variable has already been defined. See https://github.com/josegonzalez/php-dotenv#making-available-to-getenv for further usage details.

**Comment by lucasmadero** [comment]
The problem is that I develop many CakePHP 3 applications in my computer, so, when I switch from one to another, appears this error. ¿How can I avoid this kind of conflicts?
