### ISSUE TITLE
Fix for deprecated dynamic properties in php 8.2.2

### ISSUE THREAD

**Issue by fr3nch13** [josegonzalez/php-dotenv#52]
Error: Creation of dynamic property josegonzalez\Dotenv\Expect::$environment is deprecated on line 14 of vendor/josegonzalez/dotenv/src/josegonzalez/Dotenv/Expect.php

**Comment by fr3nch13** [comment]
This is passing all tests for php 5.x, 7.x, and 8.x
Coverage isn't working for php 7.1, but that's due to an internal issue with phpunit.
https://github.com/302dev/php-dotenv/actions/runs/4198159661

**Comment by fr3nch13** [comment]
PR #54 Fixes this issue and updates the CI workflow.

**Comment by fr3nch13** [comment]
See PR #55

**Comment by josegonzalez** [comment]
Closing as that was merged. Thanks for the PR!
