### ISSUE TITLE
What is `shortCircuit`?

### ISSUE THREAD

**Issue by askonomm** [josegonzalez/php-dotenv#56]
I'm creating a dotenv instance with the `createImmutable` static method, but it also takes in an optional argument called `shortCircuit`. My intuition would tell me that if I make this `false`, it would not fatal error if the .env file does not exist (which I'd really love), but it seems to not do that. There also exists no documentation on this that I can find at least.

**Comment by josegonzalez** [comment]
I think you're in the wrong project, we don't have such code here.

**Comment by askonomm** [comment]
Oh man, my bad! I had two repositories open and I opened the issue in the wrong one! Apologies.
