### ISSUE TITLE
Not getting in getenv

### ISSUE THREAD

**Issue by harikt** [josegonzalez/php-dotenv#7]
``` php
<?php
$loader = new josegonzalez\Dotenv\Loader(__DIR__ . '/.env');
// Parse the .env file
$loader->parse();
// Send the parsed .env file to the $_ENV variable
$loader->toEnv(true);
$loader->toServer(true);
echo ' ffv ' . getenv('HELLO');
var_dump($_ENV);
```

Used php's local server itself.

**Comment by mirko-pagliai** [comment]
Sorry to reopen such an old issue, but... any boolean values?
Because they weren't considered in the test and because noticeably `getenv()`/`putenv()` can't treat them as such.

**Comment by josegonzalez** [comment]
@mirko-pagliai if getenv and putenv can't, then no.
